### ISSUE TITLE
Remove the current file

### ISSUE THREAD

**Issue by becothas** [mollerhoj/telescope-recent-files.nvim#1]
When using this plugin, the current file is always the most recent. 

Could you remove the current file from the telescope dialog or reduce its ranking. Since it is not very often that one wants to open the current file :wink:

For me, the use-case would be to quickly jump to the most recent file.

**Comment by mollerhoj** [comment]
Update the extension and use:

```
-- A keymap
vim.keymap.set('n', '<leader>f', function()
  require('telescope').extensions['recent-files'].recent_files({include_current_file = false})
end, { noremap = true, silent = true })
```
