### ISSUE TITLE
Telescope extension options

### ISSUE THREAD

**Issue by okkdev** [mollerhoj/telescope-recent-files.nvim#2]
I'd like to be able to configure the extension globally from the `telescope.setup({ extensions = { recent-files = { opts... } } })` field like most other extensions. I have my `find_command` defined in a variable as I need it for multiple pickers. If I pass that variable to recent files on every invocation, the `table.remove(find_command, 1)` line starts to mutate the variable defined in my config and recent files stops working after the first invocation. 😅

**Comment by mollerhoj** [comment]
Maybe I’m thickheaded, but I dont really understand what youre asking for here: Can you show an example or something, or try and rephrase the question? I’ll be happy to accept a PR - the code is a single file and already quite hacky, I’ll likely accept any PR that works
